#!/usr/bin/env python

import sys
import numpy as np
from phot2lc.photfunc import reconfig

"""
Script which runs the reconfig function.
This will allow a user to change deafult
phot2lc parameters.

Author: 
    Zach Vanderbosch

For a description of updates, see the 
version_history.txt file.

"""

reconfig()


