import numpy as np

"""
Script containing information for each
telescope

Author: 
    Zach Vanderbosch

For a description of updates, see the 
version_history.txt file.
"""

# For new entries, follow the given format:
#
# telename: Name of telescope used
# instname: Name of instrument used
# code    : 4-letter code for this entry
# objname : FITS keyword for name of the object observed (None if unavailable or unused)
# filter  : FITS keyword for filter used for observations
# observer: FITS keyword for name or initials of observer
# date    : FITS keyword for UTC date of observation
# time    : FITS keyword for UTC time of observation (None if unavailable or unused)
# texp    : FITS heyword for exposure time of observation
# dformat : number describing the date format
#               0 = YYYY MM DD with any kind of separator
#               1 = YYYY-MM-DDThh:mm:ss (ISOT format)
#               2 = Julian Date
# tformat : number describing the time format
#               0 = hh mm ss with any kind of separator and 
#                   with or without fractional seconds
#               1 = get time from date when dformat = 1 or 2
# dark    : Dark noise for instrument in e-/s/pixel or ADU/s/pixel (np.nan if unavailable)
# read    : Read noise for instrument in e-/pixel or ADU/pixel (np.nan if unavailable)
# gain    : Gain in e-/ADU if read and dark are in e- units. or 1.0 otherwise


def get_telinfo():

    tele_info = [
        {
            "telename":"McDonald 2.1m",
            "instname":"ProEM",
            "code"    :"mcd2",
            "objname" :"OBJECT",
            "filter"  :"FILTER",
            "observer":"OBSERVER",
            "date"    :"DATE-OBS",
            "time"    :"TIME-OBS",
            "texp"    :"EXPTIME",
            "dformat" :0,
            "tformat" :0,
            "dark"    :1.6,
            "read"    :6.1,
            "gain"    :0.87
        },
        {
            "telename":"McDonald 2.7m",
            "instname":"Coude Guide",
            "code"    :"coud",
            "objname" :"OBJECT",
            "filter"  :"FILTER",
            "observer":"OBSERVER",
            "date"    :"DATE-OBS",
            "time"    :"UT",
            "texp"    :"EXPTIME",
            "dformat" :0,
            "tformat" :0,
            "dark"    :np.nan,
            "read"    :np.nan,
            "gain"    :1.00
        },
        {
            "telename":"Perkins 1.8m",
            "instname":"PRISM",
            "code"    :"perk",
            "objname" :None,
            "filter"  :"FILTNME3",
            "observer":"OBSERVER",
            "date"    :"DATE-OBS",
            "time"    :None,
            "texp"    :"EXPTIME",
            "dformat" :1,
            "tformat" :1,
            "dark"    :np.nan,
            "read"    :np.nan,
            "gain"    :1.00
        },
        {
            "telename":"PJMO 0.6m",
            "instname":"Roper PVCAM",
            "code"    :"pjmo",
            "objname" :"OBJECT",
            "filter"  :"FILTER",
            "observer":"OBSERVER",
            "date"    :"JD",
            "time"    :None,
            "texp"    :"EXPTIME",
            "dformat" :2,
            "tformat" :1,
            "dark"    :np.nan,
            "read"    :12.96,
            "gain"    :1.73
        },
        {
            "telename":"LCOGT 1.0m",
            "instname":"Sinistro",
            "code"    :"lco1",
            "objname" :"OBJECT",
            "filter"  :"FILTER",
            "observer":"USERID",
            "date"    :"DATE-OBS",
            "time"    :None,
            "texp"    :"EXPTIME",
            "dformat" :1,
            "tformat" :1,
            "dark"    :0.002,
            "read"    :7.60,
            "gain"    :1.00
        },
        {
            "telename":"KPED 2.1m",
            "instname":"KPED",
            "code"    :"kped",
            "objname" :"OBJECT",
            "filter"  :"FILTER",
            "observer":"OBSERVER",
            "date"    :"DATE-OBS",
            "time"    :"TIME-OBS",
            "texp"    :"EXPTIME",
            "dformat" :0,
            "tformat" :0,
            "dark"    :np.nan,
            "read"    :np.nan,
            "gain"    :1.00
        },
        {
            "telename":"Palomar 200in",
            "instname":"CHIMERA",
            "code"    :"p200",
            "objname" :"OBJECT",
            "filter"  :"FILTER",
            "observer":"OBSERVER",
            "date"    :"DATE-OBS",
            "time"    :"TIME-OBS",
            "texp"    :"EXPTIME",
            "dformat" :0,
            "tformat" :0,
            "dark"    :np.nan,
            "read"    :np.nan,
            "gain"    :1.00
        },
        {
            "telename":"OPD 1.6m",
            "instname":"Cam1+Ixon",
            "code"    :"opd",
            "objname" :"OBJECT",
            "filter"  :"FILTER",
            "observer":"OBSERVER",
            "date"    :"DATE-OBS",
            "time"    :None,
            "texp"    :"EXPTIME",
            "dformat" :1,
            "tformat" :1,
            "dark"    :np.nan,
            "read"    :np.nan,
            "gain"    :1.00
        },
        {
            "telename":"SARA RM",
            "instname":"SARA-RM Andor Ikon-L",
            "code"    :"sarm",
            "objname" :"OBJECT",
            "filter"  :"FILTER",
            "observer":"OBSERVER",
            "date"    :"DATE-OBS",
            "time"    :None,
            "texp"    :"EXPTIME",
            "dformat" :1,
            "tformat" :1,
            "dark"    :np.nan,
            "read"    :np.nan,
            "gain"    :1.00
        },
        {
            "telename":"SARA KP",
             "instname":"Arc Camera",
             "code"    :"sakt",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.00
        },
        {
            "telename":"SARA KP",
             "instname":"Arc Camera",
             "code"    :"sakp",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.00
         },
         {
             "telename":"SARA CT",
             "instname":"Andor Camera",
             "code"    :"sact",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.00
         },
         {
             "telename":"Amagi Observatory",
             "instname":"E-4240bi",
             "code"    :"amag",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.00
         },
         {
             "telename":"Mt. Suhora Obs. Small Dome",
             "instname":"SBIG ST-10 Dual CCD Camera",
             "code"    :"suho",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.00
         },
         {
             "telename":"61 inch Mt. Bigelow",
             "instname":"mont4k",
             "code"    :"stew",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :6.58,
             "gain"    :3.16
          },
          {
             "telename":"Lulin 1m, LOT",
             "instname":"Andor CCD/EMCCD (SDK2)",
             "code"    :"luli",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :"TIME-OBS",
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :0,
             "dark"    :np.nan,
             "read"    :8.5,
             "gain"    :2.00
          },
          {
             "telename":"1m RCC Telescope at Piszkéstető Observatory, Hungary",
             "instname":"sicamera",
             "code"    :"pisz",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"UNIXUSER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.00
          },
          {
             "telename":"ADU60 at Adiyaman Observatory, Turkey",
             "instname":"Andor CCD/EMCCD (SDK2)",
             "code"    :"adu60",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.00
          },
          {
             "telename":"Krakow 50 cm",
             "instname":"QHY-600M",
             "code"    :"krak50",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :"TIME-OBS",
             "texp"    :"EXPTIME",
             "dformat" :0,
             "tformat" :0,
             "dark"    :np.nan,
             "read"    :12.9,
             "gain"    :16.00
          },
          {
             "telename":"Remote 14inch run by Krakow Observatory, by Ukraine border",
             "instname":"ASI Camera",
             "code"    :"tymce",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :0.4386
          },
          {
             "telename":"HAO68 at Horten Observatory, Norway",
             "instname":"Moravian Instruments, G2-1600 MkII",
             "code"    :"hao",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.5
          },
          {
             "telename":"ARCSAT 0.5m at Apache Point",
             "instname":"dcam-spare",
             "code"    :"ap05",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.0
          },
          {
             "telename":"CDK500 at Krakow",
             "instname":"Apogee USB/Net",
             "code"    :"cdk500",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :12.817136,
             "gain"    :1.30117
          },
          {
             "telename":"3.5m DOT at ARIES",
             "instname":"TIRCAM2",
             "code"    :"dot",
             "objname" :"OBJECT",
             "filter"  :"FILTER1",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.0
          },
          {
             "telename":"Xinglong 0.6m telescope",
             "instname":"CCD",
             "code"    :"xing60",
             "objname" :"OBJ_NAME",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :"TIME-OBS",
             "texp"    :"EXPTIME",
             "dformat" :0,
             "tformat" :0,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.0
          },
          {
             "telename":"Xinglong 0.8m telescope, TNT",
             "instname":"CCD",
             "code"    :"tnt",
             "objname" :"OBJ_NAME",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :"TIME-OBS",
             "texp"    :"EXPTIME",
             "dformat" :0,
             "tformat" :0,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.0
          },
          {
             "telename":"Xinglong 0.85m telescope, BNT",
             "instname":"Andor Tech",
             "code"    :"bnt",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.0
          },
          {
             "telename":"Nanshan 0.43m telescope, PAT",
             "instname":"QHYCCD-Cameras2-Capture",
             "code"    :"pat",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.0
          },
          {
             "telename":"Zeiss-1000 (1m) at Tian Shan Astronomical Observatory",
             "instname":"FLI",
             "code"    :"tshao",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.0
          },
          {
             "telename":"Warwaick remote 1-meter at RM",
             "instname":"CCD",
             "code"    :"warw",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.0
         },
         {
             "telename":"Baker Observatory 20 inch, CDK20",
             "instname":"Apogee USB/Net",
             "code"    :"bake",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.0
         },
         {
             "telename":"Tuebingen Observatory 0.8m",
             "instname":"SBIG STL-1001 3 CCD Camera",
             "code"    :"tueb",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":"OBSERVER",
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :2.09
         },
         {
             "telename":"STACam on the UH88",
             "instname":"STACam",
             "code"    :"uh88",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":None,
             "date"    :"DATE",
             "time"    :"UT",
             "texp"    :"EXPTIME",
             "dformat" :0,
             "tformat" :0,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.00
         },
         {
             "telename":"Lookout Observatory 14inch, UNCA",
             "instname":"ASCOM Camera",
             "code"    :"unca",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":None,
             "date"    :"DATE-OBS",
             "time"    :None,
             "texp"    :"EXPTIME",
             "dformat" :1,
             "tformat" :1,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.00
         },
         {
             "telename":"OAN-SPM 1.5m",
             "instname":"CAMILA",
             "code"    :"oanspm",
             "objname" :"OBJECT",
             "filter"  :"FILTER",
             "observer":None,
             "date"    :"DATE-OBS",
             "time"    :"UT",
             "texp"    :"EXPTIME",
             "dformat" :0,
             "tformat" :0,
             "dark"    :np.nan,
             "read"    :np.nan,
             "gain"    :1.00
         },
         {
            "telename":"SPARC4 on OPD 1.6m",
            "instname":"SPARC4",
            "code"    :"opd16",
            "objname" :"OBJECT",
            "filter"  :"FILTER",
            "observer":"OBSERVER",
            "date"    :"DATE-OBS",
            "time"    :None,
            "texp"    :"EXPTIME",
            "dformat" :1,
            "tformat" :1,
            "dark"    :np.nan,
            "read"    :4.82,
            "gain"    :0.8
         }
    ]

    return tele_info
